"""force_rls

Revision ID: 0330ee749224
Revises: a7d6e77afc38
Create Date: 2026-07-27 20:50:51.961686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0330ee749224'
down_revision: Union[str, Sequence[str], None] = 'a7d6e77afc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables_for_rls = ['users', 'conversations', 'messages', 'agents']
    for table in tables_for_rls:
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables_for_rls = ['users', 'conversations', 'messages', 'agents']
    for table in tables_for_rls:
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###
