"""fastapi_users_fields

Revision ID: a7d6e77afc38
Revises: 63c2db724b0a
Create Date: 2026-07-27 20:47:09.806382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d6e77afc38'
down_revision: Union[str, Sequence[str], None] = '63c2db724b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE users, conversations, messages, agents CASCADE;")
    op.execute("DELETE FROM messages WHERE org_id IS NULL;")
    op.alter_column('messages', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Update RLS policies to allow superuser bypass
    tables_for_rls = ['users', 'conversations', 'messages', 'agents']
    for table in tables_for_rls:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_policy ON {table};")
        policy_sql = f"""
        CREATE POLICY {table}_org_policy ON {table}
            USING (current_setting('app.is_superuser', true) = 'true' OR org_id = current_setting('app.current_org', true)::uuid);
        """
        op.execute(policy_sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'role')
    op.alter_column('messages', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Revert RLS policies back to org_id only
    tables_for_rls = ['users', 'conversations', 'messages', 'agents']
    for table in tables_for_rls:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_policy ON {table};")
        policy_sql = f"""
        CREATE POLICY {table}_org_policy ON {table}
            USING (org_id = current_setting('app.current_org', true)::uuid);
        """
        op.execute(policy_sql)
    # ### end Alembic commands ###
